### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by spetter1337** [lolouk44/xiaomi_mi_scale#48]
**Describe the bug**
pi@goforit:~ $ bash /home/pi/scaleish/wrapper.sh
 
-------------------------------------
2021-11-10 00:46:37 - Starting Xiaomi mi Scale...
2021-11-10 00:46:37 - Loading Config From Options.json...
2021-11-10 00:46:37 - Config Loaded...
Traceback (most recent call last):
  File "/home/pi/scaleish/Xiaomi_Scale.py", line 298, in <module>
    main()
  File "/home/pi/scaleish/Xiaomi_Scale.py", line 264, in main
    discovery()
  File "/home/pi/scaleish/Xiaomi_Scale.py", line 156, in discovery
    tls=MQTT_TLS
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 241, in single
    protocol, transport, proxy_args)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/publish.py", line 176, in multiple
    client.connect(hostname, port, keepalive)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Expected behaviour**
Expected the scripts to run successfully.

**Scale (please complete the following information):**
 - Model: Xiaomi Smart Scale 2 

**Desktop/Server (please complete the following information):**
 - Docker or manually ran after a Git Clone? Docker
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC] Raspberry Pi 4
 - Bluetooth device used [e.g. Built-in, USB Dongle] Built-in

**Comment by lolouk44** [comment]
Your error states "Connection refused"
Can you double check your mqtt connection details?
Can you connect to your mqtt broker with the  same  details when using a
different app (like mqtt Explorer for example)?

**Comment by spetter1337** [comment]
For some reason, the MQTT module didnt get installed. I now completed that and also ran the bash with sudo and it worked! Only config of Home Assistant left :D 


2021-11-10 21:37:32 - Starting Xiaomi mi Scale...
2021-11-10 21:37:32 - Loading Config From Options.json...
2021-11-10 21:37:32 - Config Loaded...
2021-11-10 21:37:32 - Discovery Completed...
2021-11-10 21:37:32 - Publishing data to topic miscale/Simon/weight: {"weight":80.00,"weight_unit":"kg","bmi":24.42,"basal_metabolism":1706.20,"visceral_fat":12.50,"timestamp":"2021-11-10 21:37:32.497355"}
2021-11-10 21:37:32 - Data Published ...
2021-11-10 21:39:21 - Publishing data to topic miscale/Simon/weight: {"weight":80.15,"weight_unit":"kg","bmi":24.47,"basal_metabolism":1708.44,"visceral_fat":12.57,"timestamp":"2021-11-10 21:39:21.775211"}
2021-11-10 21:39:21 - Data Published ...
2021-11-10 21:41:40 - Publishing data to topic miscale/Simon/weight: {"weight":80.30,"weight_unit":"kg","bmi":24.51,"basal_metabolism":1710.67,"visceral_fat":12.65,"timestamp":"2021-11-10 21:41:40.207222"}
2021-11-10 21:41:40 - Data Published ...

**Comment by spetter1337** [comment]
When I do "docker container ls" in the terminal, it says that the container is restarting. Is that suppose to be the case?

d5621dcd3f2b   
lolouk44/xiaomi-mi-scale:latest                            
"/entrypoint.sh /cmd…"   
23 hours ago   
Restarting (1) 17 seconds ago

**Comment by lolouk44** [comment]
no it should not restart. You should see things in the logs if it doesn't work correctly. 
Is there anything else than what you already posted?
Alternatively if you use docker-compose, run it without the  `-d` so you see all the logs in the terminal

**Comment by spetter1337** [comment]
Hm... I have successfully managed to get the data streaming into Home Assistant now - i.e. when get on the scale, new data pops up in HA will the correct metrics. Did the HA MQTT integration

**Comment by spetter1337** [comment]
Getting the following errors in the logs though:

2021-11-10 21:30:16 - Starting Xiaomi mi Scale...
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 39, in <module>
    with open('/data/options.json') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/options.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 139, in <module>
    sys.stderr.write(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - options.json file missing... {error}\n")
NameError: name 'error' is not defined

**Comment by spetter1337** [comment]
My options.json path is: /home/pi/scaleish/options.json. Guess that's why the issue occurs? However, where am I suppose to do the replacement?

**Comment by lolouk44** [comment]
So you found a bug in my code. Thanks 👍 
However it's just a cosmetic bug that has nothing to do with your issue 😶 
The issue is indeed where you've saved your file
Check your docker-compose file
You should have something that looks like this:
```

      volumes:
        - /home/pi/scaleish:/data
```
Provided there is just options.json in that folder (just in case)
If unsure, create a sub folder (e.g. data) and move options.json in it, then map it in your docker-compose file

**Comment by spetter1337** [comment]
Thank you! I had the default volume that you had in your file here at github, so that makes sense. 

Just one newbie question: I have now edited the docker-compose.yml file - what command do I need to write into the terminal in order for the container to be updated? Tried restarting the container but didn't change anything.

**Comment by lolouk44** [comment]
go where the docker-compose.yml is located and type `docker-compose down && docker-compose up -d`
This will stop any existing container and restart

**Comment by spetter1337** [comment]
Thanks, much appreciated. Looooove this, gonna pull everything into Splunk later. 

Now I get it, the container is used as a mean to execute the scripts and initiate MQTT between the scale and the raspberry.  But because I used bash before - i.e "Running script directly on your host system" - I was still able to get the MQTT up and running, however, using the container seems more convenient as it won't require having the CLI open etc.

**Comment by lolouk44** [comment]
docker is the way to go. No need to worry about dependencies or about having to install additional apps.
Glad I could help.

**Comment by spetter1337** [comment]
A question with regards to the volume in the docker-compose file.

   volumes:
        - /home/pi/scaleish:/data
        
 I have tried to do some googling to understand the logic behind it, but I still don't quite get it. Is my idea of it stated below correct to some extent?
 
 * /home/pi/scaleish = defines the path on the host where the necessary resources are stored for the container to run (xiaomi python scripts, options.json etc)
 * /data = the directory in the container that will be mapped to the /home/pi/scaleish, completing the resource integration enabling the container to retrieve the resources from the host and run successfully
 
 Thanks!

**Comment by lolouk44** [comment]
Hi. You're spot on
